name: Main Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _site/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: github-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}